### ISSUE TITLE
#Exception1 您好，我在使用过程中遇到了错误，

### ISSUE THREAD

**Issue by oldoldcoder** [zzwtsy/ChangJiangYuKeTang#1]
![图片](https://user-images.githubusercontent.com/83199123/200747701-7aa9d312-89c5-4467-b364-a9ebb2996d58.png)
在选择了相应的课程之后，在176行遇到了错误，我配置的token都是正确的，希望您能修改代码，我会叫上好朋友来为你的项目点上start
这是报错时候参数信息：
![图片](https://user-images.githubusercontent.com/83199123/200748052-42330fcf-fc62-4cf2-bd6d-4520be933f07.png)
![图片](https://user-images.githubusercontent.com/83199123/200748089-ee0cc0af-d90f-4803-ae01-1fd59cac751d.png)
本人python不是很熟悉，希望您能在空闲时间看看

**Comment by oldoldcoder** [comment]
thx

**Comment by zzwtsy** [comment]
可以将ret信息打印出来发给我吗
![屏幕截图 2022-11-09 221453](https://user-images.githubusercontent.com/58852496/200853320-c0517c65-1057-4b9d-a049-9ae84b5e5420.png)

**Comment by zzwtsy** [comment]
> ![图片](https://user-images.githubusercontent.com/83199123/200747701-7aa9d312-89c5-4467-b364-a9ebb2996d58.png) 在选择了相应的课程之后，在176行遇到了错误，我配置的token都是正确的，希望您能修改代码，我会叫上好朋友来为你的项目点上start 这是报错时候参数信息： ![图片](https://user-images.githubusercontent.com/83199123/200748052-42330fcf-fc62-4cf2-bd6d-4520be933f07.png) ![图片](https://user-images.githubusercontent.com/83199123/200748089-ee0cc0af-d90f-4803-ae01-1fd59cac751d.png) 本人python不是很熟悉，希望您能在空闲时间看看


不用发ret信息了，从第三张图片上看原因是没用获取到课程信息数据

**Comment by zzwtsy** [comment]
我在dev分支改了一下代码，你可以试试能不能运行

**Comment by oldoldcoder** [comment]
好的谢谢，我这下试试，早上有课没仔细看不好意思

**Comment by oldoldcoder** [comment]
> 我在dev分支改了一下代码，你可以试试能不能运行

好的谢谢你

**Comment by oldoldcoder** [comment]
> 我在dev分支改了一下代码，你可以试试能不能运行

![图片](https://user-images.githubusercontent.com/83199123/201016386-0e16e858-b070-402e-bd17-549b68223d08.png)
会到watch_video分支的错误那一行，不过雨课堂这里显示的都是已经刷完，请问要不要debug信息

**Comment by zzwtsy** [comment]
> > 我在dev分支改了一下代码，你可以试试能不能运行
> 
> ![图片](https://user-images.githubusercontent.com/83199123/201016386-0e16e858-b070-402e-bd17-549b68223d08.png)会到watch_video分支的错误那一行，不过雨课堂这里显示的都是已经刷完，请问要不要调试信息

如果可以的话请发一下错误信息，我看一看

**Comment by oldoldcoder** [comment]
> > > 我在dev分支改了一下代码，你可以试试能不能运行
> > 
> > 
> > ![图片](https://user-images.githubusercontent.com/83199123/201016386-0e16e858-b070-402e-bd17-549b68223d08.png)会到watch_video分支的错误那一行，不过雨课堂这里显示的都是已经刷完，请问要不要调试信息
> 
> 如果可以的话请发一下错误信息，我看一看

好的我中午试试给您发报错信息
